name: gcf_network_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.12
  - pandas=2.3.3
  - numpy=2.3.3
  - networkx=3.5
  - scikit-learn=1.7.2
  - scipy=1.16.3
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - python-louvain=0.16
  - statsmodels=0.14.5
  - pyyaml=6.0.3
  - tqdm
  - pip